name: Battle Craft
env: dev

sock_file: /run/battle.socket
port: 37221

db:
    default: 
        type: mysql
        dsn:  root:d@(localhost:3306)/battle

    hehe: 
        type: mysql
        dsn:  root:d@(localhost:3306)/battle

