-
    name: ~
    pattern: ~
    routes:
        -
            name: main
            pattern: /
        -
            name: user
            pattern: /signin
        -
            name: user
            pattern: /signup
        -
            name: user
            pattern: /signout


-
    name: ~
    pattern: /map
    routes:
        -
            name: map_main
            pattern: /

        -
            name: map_scan
            pattern: /scan

        -
            name: map_rect
            pattern: /rect

        -
            name: map_sum
            pattern: /sum

        -
            name: map_refresh
            pattern: /refresh

-
    name: ~
    pattern: /base
    routes:
        -
            name: base_settle_down
            pattern: settle_down

