-
    prefix: ~
    routes:
        -
            name: index
            controller: main
            action: Index
            pattern: /
        -
            name: ws_index
            controller: main
            action: Ws
            pattern: /ws

-
    prefix: /map
    routes:
        -
            name: map_scan
            controller: map
            action: Scan
            pattern: /scan
        -
            name: map_sum
            controller: map
            action: Sum
            pattern: /sum

